### ISSUE TITLE
Hot code reloading with Docker

### ISSUE THREAD

**Issue by cvdub** [timonweb/django-tailwind#72]
Does anyone know how to get hot code reloading working in a Docker container?

**Comment by swdevbali** [comment]
My problem also: https://dev.to/aspraveen/django-with-tailwind-jit-and-hot-reloading-i9i/comments
I already expose the port, which I guess it is `8383` based on `bs.config.js`, opening localhost:8383 gives me directory list containig `tailwind.config.js` among other thing.

But not yet hot reloading tho.

**Comment by timonweb** [comment]
Hi, I haven't tried to do it with Docker. My understanding is that you need to have two services based off the same Dockerfile. One should run Django dev server via `python manage.py runserver`, another runs Tailwind in dev mode via `python manage.py tailwind start`. The Tailwind server should also expose port `8383` and map it to the port `8383` on your host machine. In theory it should all click, but I haven't tried, I don't use Docker for dev.

So if anyone manages to create a working setup, feel free to share it here, I'll add it to the example project.

**Comment by timonweb** [comment]
Hey I took a stab and created a Docker example, check it here: https://github.com/timonweb/django-tailwind/tree/master/example

**Comment by swdevbali** [comment]
Woa. Checking that!

**Comment by swdevbali** [comment]
Well, still the same tho: I tried to debug it while showing how it goes: https://www.youtube.com/watch?v=PFP8Hdh1Ja0
I kinda expecting if I change the html/css, it will actively refresh it without reloading the page.
That what should happen, right?
But still not there.

I am in Windows 10 btw

**Comment by BasilPH** [comment]
I got it to work with Docker. I added another service that uses exactly the same image as my Django container. But instead of starting Django, I start the tailwind command:

```yaml
version: '3'

services:
  tailwind:
    image: django-image
    container_name: tailwind
    volumes:
      - .:/app:z
    command: bash -c "python manage.py tailwind install && python manage.py tailwind start"
    restart: "unless-stopped"
    ports:
      - "8383:8383"
```

However, I ran into another issue: The browser-sync script did not show up for me when I included the `{% tailwind_css %}
` tag. It seems like the [django.template.context_processors.debug](https://docs.djangoproject.com/en/3.2/ref/templates/api/#django-template-context-processors-debug) doesn't work. In my case `{%if debug %}` is always false. This might be because of docker, as it changes the IP addresses. If you want to add your docker internal address, you can use this trick from [cookiecutter-django](https://cookiecutter-django.readthedocs.io/en/latest/):

```python
import socket

hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS += [".".join(ip.split(".")[:-1] + ["1"]) for ip in ips]
```

This didn't work for me either, most likely because I use Nginx in development. We had the same issue with the django-debug toolbar, which wouldn't show if we use nginx in development. 

Until I can figure out to get `{%if debug %}` to work again, I just add the browser-sync script directly to my base.html:

```html
   <script id="__bs_script__">//<![CDATA[
  document.write("<script async src='//HOST:8383/browser-sync/browser-sync-client.js'><\/script>".replace("HOST", location.hostname));
  //]]></script>
```
I know that using `INTERNAL_IPS` is the new way to do this, but it breaks with more complex development setups. Have you ever considered adding an explicit setting that we could put into the settings file to force the inclusion of browser-sync @timonweb ? We could then do something like `FORCE_SYNC=DEBUG` in the settings, which I think would be neat.

**Comment by timonweb** [comment]
@BasilPH yes, I think we need to add something like this, I'd call it `TAILWIND_DEV_MODE=DEBUG`. Will add when I get some free time.

**Comment by kpavlovsky** [comment]
Debug toolbar has a callback function to decide if it needs to be shown. Maybe adopt the same approach?

**Comment by timonweb** [comment]
In the upcoming `2.2` version I added `TAILWIND_DEV_MODE` variable. Feel free to test-drive it here: https://pypi.org/project/django-tailwind/2.2.0b2/
