### ISSUE TITLE
App should make an attempt to retrieve the NPM path

### ISSUE THREAD

**Issue by MichaelGatesDev** [timonweb/django-tailwind#83]
I am just getting started with django-tailwind and I received the following error:

```
CommandError: 
It looks like node.js and/or npm is not installed or cannot be found.

Visit https://nodejs.org to download and install node.js for your system.

If you have npm installed and still getting this error message, set NPM_BIN_PATH variable in settings.py to match path of NPM executable in your system.

Example:
NPM_BIN_PATH = "/usr/local/bin/npm"
```

The error makes it seem like the app tried to find a path to NPM or actually tried to use it. But [according to this file](https://github.com/timonweb/django-tailwind/blob/c5253cd54d482f3e02f4df3ee07008ee09c47419/src/tailwind/npm.py#L15), it will only ever be retrieved from a django settings file.  

I think that it is quite likely that a user's system has NPM installed globally, so if a user does not explicitly set `NPM_BIN_PATH`, it should just assume that `npm` is available globally and should attempt to run the subprocess as `subprocess.run(["npm"] + list(args), cwd=self.cwd)` ([how to run npm in subprocess without an absolute path to the executable](https://stackoverflow.com/a/28903670/1925638)).

**Comment by justinmayer** [comment]
I believe the project already behaves as you propose, since as the [corresponding documentation](https://github.com/timonweb/django-tailwind/blob/1a8094711074a3fbf90ca902f636a5d37508cc32/docs/installation.md#configuration-of-the-path-to-the-npm-executable) states, the default value of `NPM_BIN_PATH` is `npm`.

Following the principle of "explicit is better than implicit", I don't think Django-Tailwind should do any more than it currently does to locate the NPM executable. As noted in the above documentation, if Django-Tailwind can't find the executable, instructions are clearly provided regarding how to specify the desired executable. (And there can often be multiple NPM executables on a system, ergo why being explicit is preferred.)

**Comment by timonweb** [comment]
@MichaelGatesDev you can change `npm` bin path as stated in the docs. Please see a link in James' comment above.
